version: '3.3'

services:
  #service 1: definition of mysql database
  db:
    image: mysql:latest
    container_name: mysql-database17
    environment:
      - MYSQL_ROOT_PASSWORD=spring
    ports:
      - "3306:3306"

    restart: always

  cache:
    image: "redis"
    container_name: redis1
    ports:
      - "6379:6379"
    restart: always

    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL



  #service 3: definition of your spring-boot app
  customerservice:                        #it is just a name, which will be used only in this file.
    image: property-service               #name of the image after dockerfile executes
    container_name: api  #name of the container created from docker image
    build:
      context: .                          #docker file path (. means root directory)
      dockerfile: Dockerfile              #docker file name
    ports:
      - "8080:8080"                       #docker containter port with your os port

    restart: always

    environment:
       SPRING_REDIS_HOST: cache
       SPRING_REDIS_PORT: 6379
    depends_on:                           #define dependencies of this app
      - db                                #dependency name (which is defined with this name 'db' in this file earlier)
      - cache




        