version: '3.3'

services:
  #service 1: definition of mysql database
  db:
    image: mysql:latest
    container_name: mysql-database17
    environment:
      - MYSQL_ROOT_PASSWORD=spring
    ports:
      - "3306:3306"
    restart: always

  cache:
    image: "redis"
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL



  #service 3: definition of your spring-boot app
  customerservice:                        #it is just a name, which will be used only in this file.
    image: property-service               #name of the image after dockerfile executes
    container_name: property-service-app17  #name of the container created from docker image
    build:
      context: .                          #docker file path (. means root directory)
      dockerfile: Dockerfile              #docker file name
    ports:
      - "8081:8080"                       #docker containter port with your os port
    restart: always

    depends_on:                           #define dependencies of this app
      - db                                #dependency name (which is defined with this name 'db' in this file earlier)
      - cache
    environment:
      SPRING_APPLICATION_JSON: '{
              "spring.datasource.url": "jdbc:mysql://mysql-database17:3306/selecao_builders?createDatabaseIfNotExist=true",
              "spring.datasource.username": "root",
              "spring.datasource.password": "spring",
              "spring.datasource.driver-class-name": "com.mysql.jdbc.Driver",
              "spring.mvc.pathpattern.matching-strategy": "ANT_PATH_MATCHER"
        }'
        
        