spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:9906/selecao_builders?createDatabaseIfNotExist=true
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: 'true'
    hibernate:
      ddl-auto: update
  mvc:
      pathmatch:
        matching-strategy: ANT_PATH_MATCHER

  cache:
    type: redis
    redis:
      host: localhost
      port: '6379'

server:
  port: 8081
  error:
    include-stacktrace: never

      